(Source react)
(Cfg_str project_name reason-todomvc)
(Cfg_str project_slug reason-todomvc)
(Cfg_str project_description"TodoMVC implementation written in ReasonML")
(Cfg_str author_name"Hyeseong Kim <cometkim.kr@gmail.com>")
(Cfg_str css_framework None)
